<?xml version="1.0"?>
<package format="3">
  <name>fire_scout_bringup</name>
  <version>0.2.0</version>
  <description>Minimal Fire Scout single-UAV simulation bringup.</description>
  <maintainer email="wei@example.com">wei</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>fire_scout_localization</exec_depend>
  <exec_depend>fire_scout_sensors</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
