<?xml version="1.0"?>

<package format="3">

  <name>fire_scout_control</name>

  <version>0.0.1</version>

  <description>
    PX4 control nodes for Fire Scout UAV simulation.
  </description>

  <maintainer email="wei@example.com">
    wei
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>
    ament_cmake
  </buildtool_depend>

  <depend>
    rclcpp
  </depend>

  <depend>
    px4_msgs
  </depend>

  <depend>
    sensor_msgs
  </depend>


  <export>
    <build_type>
      ament_cmake
    </build_type>
  </export>

</package>